name: Deploy to DreamHost

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to DreamHost via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DH_HOST }}
          username: ${{ secrets.DH_USER }}
          key: ${{ secrets.DH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ${{ secrets.DH_PATH }}
            git reset --hard
            git clean -fd
            git pull origin main
