name: Deploy to DreamHost

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # ✅ Optional: Setup Node.js for build tools like Sass/Vite
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # ✅ Install dependencies if package.json exists
      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            npm ci
          else
            echo "No package.json found. Skipping dependency install."
          fi

      # ✅ Build assets
      - name: Run build
        run: |
          if [ -f package.json ]; then
            npm run build || echo "No build script found. Skipping build."
          else
            echo "No package.json found. Skipping build."
          fi

      # ✅ Deploy theme/code to DreamHost
      - name: Deploy theme/code via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DH_HOST }}
          username: ${{ secrets.DH_USER }}
          key: ${{ secrets.DH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ${{ secrets.DH_PATH }}
            git reset --hard
            git clean -fd
            git pull origin main
            echo '<?php if (function_exists("opcache_reset")) opcache_reset();' | php

      # ✅ Upload new media files via rsync
      - name: Sync media files via rsync
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --ignore-existing
          path: ./wp-content/uploads/
          remote_path: ${{ secrets.DH_UPLOADS_PATH }}
          remote_host: ${{ secrets.DH_HOST }}
          remote_user: ${{ secrets.DH_USER }}
          remote_key: ${{ secrets.DH_PRIVATE_KEY }}
